### ISSUE TITLE
[BUG] Infinite Edge can't find TFT events for download

### ISSUE THREAD

**Issue by Neinndall** [Hi-Ray/infinityedge#10]
**Describe the bug**
Practically when infinite finds the events for download, only the LOL events appear in the console, not the event that is currently active at: https://clientconfig.rpg.riotgames.com/api/v1/config/public?namespace=lol.client_settings.tft with the URL: https://embed.rgpub.io/wwpub-tft-soul-fighter-embed-2023/{bcplocale}/

**To Reproduce**
Steps to reproduce the behaviour:
1. Ejecute Infinite Edge

**Expected behaviour**
That in addition to the LOL events, you can download the TFT event or events correctly.

**Screenshots**
there's no need

**Desktop (please complete the following information):**
 - OS: Win
 - Version 10

**Comment by Hi-Ray** [comment]
More info needed

**Comment by Neinndall** [comment]
u fixed this Ray in the patch 13.14, but u dont close it XD
