### ISSUE TITLE
[Feature] Possibility to download all the assets of METAGAMES events

### ISSUE THREAD

**Issue by Neinndall** [Hi-Ray/infinityedge#11]
**Describe the feature**
From: https://embed.rgpub.io/mgs-soul-fighter-2023/en-us

Riot has added a new metagame with a lot of assets, very similar to the sentinels of light event, where there is a story mode with sprints, text among other important assets that really from what I have investigated are not located in the event address as normal events that assets are located in the typical app.js or dist.js.

From what I have verified to be unity, in an address: 
- https://embed.rgpub.io/mgs-soul-fighter-2023/webgl/StreamingAssets/aa/catalog.json

Which here are mostly the assets of the different characters, maps, location, among others, obviously the full address is not really there, but from what I have been able to verify the URL from where it starts for the assets is: 
- `https://embed.rgpub.io/mgs-soul-fighter-2023/webgl/StreamingAssets/aa/`

If we accompany for example: `/WebGL/motioncomics_assets_motioncomic_soulfighter_intro_651b7bba461d66ebde947f9c8fb0a69f.bundle`

and we get: https://embed.rgpub.io/mgs-soul-fighter-2023/webgl/StreamingAssets/aa//WebGL/motioncomics_assets_motioncomic_soulfighter_intro_651b7bba461d66ebde947f9c8fb0a69f.bundle

to the previous address, we will download the unity file where it contains several assets, I don't know if you can add this type of events for download to this tool, I have given the information that I have researched, I hope it will be useful.

**Comment by Hi-Ray** [comment]
I'm not sure if I mentioned this here however i do not feel like i we will add this to infinityedge, The reason for this is I doubt there are tools that will allow for us to maintain cross platform compatibility and most likely the simplicity of things. 

If there is a case where there are libraries we can utilise that make things simpler I would love to incorporate it.

However for now I will close this issue but it can be reopened in the future as I may consider writing a library to complete this task or hopefully someone will make one by then.

Thank you for the great feature request though.
