### ISSUE TITLE
[BUG] Infinite edge creates folders that are unnecessary

### ISSUE THREAD

**Issue by Neinndall** [Hi-Ray/infinityedge#12]
**Describe the bug**
When infinite creates the corresponding folders and downloads the assets I have observed that it creates in: events/lol/<name of event>/here
Folders that do not contain anything, which later is actually inside the "images" folder where they really are again with their respective assets.
For example, in the current soul fighter event, I show an image where it creates the _generated folder that is empty and several folders of the different champion skins of the event that are empty, but then if we enter the "images" folder they find their respective assets.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run infinite

**Expected behaviour**
Don't create unnecessary folders without files.

**Screenshots**
Added.
![image](https://github.com/Hi-Ray/infinityedge/assets/66384195/39d33ea5-39cf-4eea-a23a-cfde525d1d8e)

![image](https://github.com/Hi-Ray/infinityedge/assets/66384195/0663fe2d-72cd-4126-a73b-7474edbaa503)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Hi-Ray** [comment]
I am currently looking into this as there maybe certain assets infinityedge is missing however if this is not the case [0c43b2b](https://github.com/Hi-Ray/infinityedge/commit/0c43b2ba9bbc4e015f060da0921207ccb87642c3) should fix the empty directory issue. 

I will close this as the commit mentioned above fixes this.
