### ISSUE TITLE
[BUG] Duplicate assets with different names

### ISSUE THREAD

**Issue by Neinndall** [Hi-Ray/infinityedge#13]
**Describe the bug**
For example, in the new soul fighter event, infinite edge downloads all the assets of the event but it seems that it doesn't know if there could be duplicate assets, since Riot on the page from what I've seen there are duplicate assets that are the same image but something changes the name of the asset. I will attach an image so that it is understood.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run infinite

**Expected behaviour**
Don't download duplicate assets.

**Screenshots**
Added.

For example, in this image, where you can see the name for example: `bg-index-samira.6a5d94` there are two bg-index-samira but in the end the final part changes, so infinite is downloading this, having 2 duplicate assets and they are the same.

There are several cases, in _generated, in the root folder as seen in the image.
![image](https://github.com/Hi-Ray/infinityedge/assets/66384195/a32c960e-6316-4aa7-b672-197653afdb64)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Hi-Ray** [comment]
This is intended behaviour as the assets are named separately.
