### ISSUE TITLE
[Feature] August Event Briar: Download others files as: .ogg

### ISSUE THREAD

**Issue by Neinndall** [Hi-Ray/infinityedge#15]
**Describe the feature**
From here --> https://embed.rgpub.io/wwpub-lol-august-event-embed-2023/en-us

are in 2 formats: `ogg and m4a`, i think the best format is: `.ogg`

![image](https://github.com/Hi-Ray/infinityedge/assets/66384195/578e0c55-41fe-4846-806f-5f5747af41c5)

![image](https://github.com/Hi-Ray/infinityedge/assets/66384195/3298612a-1592-4449-b0b8-ef84fad9af08)

**Comment by Hi-Ray** [comment]
Fixed in [6e3a14f](https://github.com/Hi-Ray/infinityedge/commit/6e3a14ff2ac9986729fe031df9f495b673cdae21)
