### ISSUE TITLE
[BUG] Error downloading some assets

### ISSUE THREAD

**Issue by Neinndall** [Hi-Ray/infinityedge#3]
**Describe the bug**
Run infinity edge and fail to download some event assets.
[logs.txt](https://github.com/Hi-Ray/infinityedge/files/10406179/logs.txt)

**I only attached the files that it does not download.**

**Comment by Hi-Ray** [comment]
```
2023-01-12T22:31:10+0100 <warn> index.js:64 (downloadFiles) failed to download /fe/lol-home/icon-rp.png
2023-01-12T22:31:11+0100 <warn> index.js:64 (downloadFiles) failed to download /fe/lol-home/icon-ip.png
```

Should be normal as these are assets communitydragon raw gets from the league client which is not in the scope of universe.

**Comment by Hi-Ray** [comment]
```
2023-01-12T22:31:11+0100 <warn> index.js:64 (downloadFiles) failed to download _generated/sprite-pre-default.png
2023-01-12T22:31:12+0100 <warn> index.js:64 (downloadFiles) failed to download _generated/sprite-pre-default.jpg
```

I will look into this, but the jpeg file from what i've seen is not present for some reason so that maybe an issue out of our hands I will look into the png though.

**Comment by Hi-Ray** [comment]
Also as a note for next time please provide the full logs. Thank you

**Comment by Neinndall** [comment]
As we talk on discord, I wanted to make it as brief as possible, but if anything else, I will specify everything in more detail.

**Comment by Neinndall** [comment]
I did some tests when you released the fix that it didn't download those sprites.

There is still the same error, I give you more details:

In the **lunar event**, the same thing happens, it does not download the files **"_generated/sprite-pre-default.jpg"**

However, from the **SEASON 2023 event**, it downloads them, but from what I see from the page they are files that have nothing to view.

I leave you the entire console log.
[logs.txt](https://github.com/Hi-Ray/infinityedge/files/10425143/logs.txt)

**Comment by bangingheads** [comment]
![image](https://user-images.githubusercontent.com/53184036/213931618-1c170868-2a55-4af5-a41f-e7358d6cdd5f.png)

I'm not sure what kind of response we are looking for here these are valid responses from riot so we download them. They have correct headers and are technically valid files.

With that being said I think we are more looking for the ``_generated/sprite-global-pre-default.png`` but I'm not sure they are included in a valid way to us
