### ISSUE TITLE
[BUG and SUGGESTION] About the Riot Assets and various things

### ISSUE THREAD

**Issue by Neinndall** [Hi-Ray/infinityedge#4]
**Describe the bug + Suggestion**
From what I see, it doesn't seem to download anything from the AU "Cupcakes 4 Heartaches" event (test). 
In addition, it does not find the event (lunar) currently, in the previous version it downloaded the assets without problems. However, in "AU" there is the lunar event and it still does not download it. **Below, I propose an idea of if it could be done.**

![image](https://user-images.githubusercontent.com/66384195/220134583-8e531c6a-ee79-49fb-b222-7b0a070bba71.png)
![image](https://user-images.githubusercontent.com/66384195/220133275-18ae1aa0-03b1-4fe6-8406-a41aef0a6323.png)

On the other hand, I don't know if changing "lc_home_en_US.json" to "lc_home_en_AU.json" will affect the arrival and detection of events in one region to another. I don't know if there will be an opportunity to do one thing in the tool:

- If there is any new event in "lc_home_en_AU.json" that is not in "lc_home_en_US.json" download it and then re-download the existing ones in the main "US"
- On the other hand, I don't know if this is a bug, but I'll explain. When downloading assets from riot client I put an example here:
https://lol.secure.dyn.riotcdn.net/channels/public/rccontent/theme/manifest_default.json, there are other types of assets that should be downloaded such as: the videos found in that .json, there are also other images like the uncut full splash art that doesn't download "splash-assets/Product_Details_Background_2023.jpg", I'll attach an image.

![image](https://user-images.githubusercontent.com/66384195/220102307-55b5d65f-0ebc-4f18-8865-d148b0b153f5.png)
Infinite seems to prioritize the download of the first images and not the videos and the following images from "game_library" "product_details" as I said, the first image is the same but it is the cut image. The other .json, the same thing happens.

**To Reproduce**
Steps to reproduce the behaviour:
I run the program, it detects the (AU) event but in the end it doesn't download any asset and either the LUNAR EVENT.
![image](https://user-images.githubusercontent.com/66384195/220103427-ed618035-7bab-49e7-8077-837f406239dd.png)
There is no asset inside the event? Is rare.

**Expected behaviour**
Find assets (someone)

**Screenshots**
Added.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
No.

**Comment by Hi-Ray** [comment]
For the cupcakes event as mentioned on discord I discussed this with @bangingheads and we have agreed to manually pull these assets as the tools required would make it difficult to maintain infinityedge.

**Comment by Hi-Ray** [comment]
As for the assets missing from the riot client the current iteration is still experimental and will improve over time.

With that mentioned thank you for the bug report I will look into it.

**Comment by Neinndall** [comment]
![image](https://user-images.githubusercontent.com/66384195/220378300-dffd95bc-b00d-4301-ba55-a3cee69d9f0c.png)

and the other thing about "lc_home_en_US.json" change to "lc_home_en_AU.json" to detect events in the AU region?
Currently is not detected the lunar event, when that event is active in AU, i explain? If infinite is taking the AU manifest it is not downloading the assets of the active lunar event.

It is from what I was saying, I don't know if a small adjustment can be implemented which, that InfiniteEdge is mainly based on "https://lolstatic-a.akamaihd.net/lc-home-config/v1/live/lc_home_en_US.json " and also check "lc_home_en_AU" in case infinite find an event that is not in "US"

![image](https://user-images.githubusercontent.com/66384195/220377666-cff7ca98-bdfe-47e6-a268-99884129e514.png)

**Comment by Hi-Ray** [comment]
Like I said previously these events we will manually upload to universe on CommunityDragon.
As for the checking of the AU locale it wouldn't really benefit us afaik.
If this changes in the future we can re-evaluate it then in which case I would advise opening another issue for this entirely.

**Comment by Hi-Ray** [comment]
As of [93d958e](https://github.com/Hi-Ray/infinityedge/commit/93d958e52fc57bdf9c11d651d468a0efd61c71b6) the fetching for all assets should be fixed if any more issues arise please reopen the issue but for now I am closing this issue
