### ISSUE TITLE
[BUG] Can't find any available event

### ISSUE THREAD

**Issue by Neinndall** [Hi-Ray/infinityedge#5]
**Describe the bug**
when you run infinitedge it only downloads assets from the riot client (lor, lol, valorant etc...) but it doesn't download the available events... (now its UP milio assets)

**To Reproduce**
Steps to reproduce the behaviour:
1. run the tool

**Expected behaviour**
download the availables events assets

**Screenshots**
![image](https://user-images.githubusercontent.com/66384195/227028643-17331706-7a3f-40d6-9dbf-65d76194bb74.png)

**Desktop (please complete the following information):**
 - OS: win 10

**Comment by Hi-Ray** [comment]
Fixed in [eadc524](https://github.com/Hi-Ray/infinityedge/commit/eadc524938cfc66002e91d0edbb1c80ec6ed2a9c)
